# Jekyll test
title: Hyding in plain sight
lang: en 
languages: ["en", "de"] 
theme: jekyll-theme-tactile
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true